<a href="https://colab.research.google.com/github/RodrigoARivasG/etl-data-pipeline/blob/main/data/notebooks/etl_clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd

In [23]:
url = "https://raw.githubusercontent.com/RodrigoARivasG/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv"
df = pd.read_csv(url)
df.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [24]:
#Exploracion de datos
df.shape
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_cliente        3030 non-null   int64
 1   nombre            3030 non-null   object
 2   email             3030 non-null   object
 3   genero            2435 non-null   object
 4   fecha_nacimiento  3030 non-null   object
 5   ciudad            3030 non-null   object
 6   segmento          2433 non-null   object
dtypes: int64(1), object(6)
memory usage: 165.8+ KB

id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [25]:
#Limpieza de datos
clientes = df.copy()

# Normalizar nombres de columnas
clientes.columns = clientes.columns.str.strip().str.lower()

# Limpiar espacios en columnas de texto
for col in clientes.select_dtypes(include="object").columns:
    clientes[col] = clientes[col].astype(str).str.strip()

# Reemplazar vacíos por NA
clientes = clientes.replace(r'^\s*$', pd.NA, regex=True)
clientes = clientes.replace(['nan', 'None', '-'], pd.NA)

# Convertir id_cliente a numérico
clientes['id_cliente'] = pd.to_numeric(
    clientes['id_cliente'],
    errors='coerce'
)

# Estandarizar nombre
clientes['nombre'] = (
    clientes['nombre']
    .astype(str)
    .str.strip()
    .str.title()
)

# Estandarizar email
clientes['email'] = (
    clientes['email']
    .astype(str)
    .str.strip()
    .str.lower()
)

# Estandarizar genero
clientes['genero'] = (
    clientes['genero']
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        'masculino': 'Hombre',
        'hombre': 'Hombre',
        'm': 'Hombre',
        'femenino': 'Mujer',
        'mujer': 'Mujer',
        'f': 'Mujer'
    })
)

# Estandarizar ciudad
clientes['ciudad'] = (
    clientes['ciudad']
    .astype(str)
    .str.strip()
    .replace({
        'SanMiguel': 'San Miguel',
        'S. Miguel': 'San Miguel',
        'Sta. Ana': 'Santa Ana',
        'Sta Ana': 'Santa Ana'
    })
    .str.title()
)

# Estandarizar segmento
clientes['segmento'] = (
    clientes['segmento']
    .astype(str)
    .str.strip()
    .str.title()
)

# Convertir fecha_nacimiento a fecha
clientes['fecha_nacimiento'] = pd.to_datetime(
    clientes['fecha_nacimiento'],
    errors='coerce'
)

# Eliminar duplicados
clientes = clientes.drop_duplicates()

clientes

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011-11-24,San Miguel,<Na>
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,<na>,NaT,Santa Ana,<Na>
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Hombre,NaT,San Miguel,<Na>
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Hombre,NaT,Lalibertad,Regular
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,<na>,1945-08-02,San Salvador,Pyme
...,...,...,...,...,...,...,...
3025,3026,Ricardo Hernández Rojas (Dup),ricardo.hernandez.rojas3@gmail.com,Hombre,NaT,La Libertad,Regular
3026,3027,Luis Cruz Castillo (Dup),luis.cruz.castillo1@mail.com,<na>,NaT,San Salvador,Pyme
3027,3028,Jorge García Pérez (Dup),jorge.garcia.perez2@example.com,Hombre,NaT,San Miguel,<Na>
3028,3029,Juan García Rojas (Dup),juan.garcia.rojas4@example.com,fem,NaT,San Miguel,Pyme
3029,3030,Ana Vásquez Torres (Dup),ana.vasquez.torres5@gmail.com,female,NaT,La Libertad,Regular

Revisar nulos por columna

In [26]:
clientes.isna().sum()

id_cliente             0
nombre                 0
email                  0
genero                 0
fecha_nacimiento    2445
ciudad                 0
segmento               0
dtype: int64

Separar datos válidos y rechazados

In [27]:
validos = clientes[
    clientes['id_cliente'].notna() &
    clientes['nombre'].notna() &
    clientes['email'].notna() &
    clientes['genero'].notna() &
    clientes['fecha_nacimiento'].notna() &
    clientes['ciudad'].notna()
].copy()

rechazados = clientes[
    clientes['id_cliente'].isna() |
    clientes['nombre'].isna() |
    clientes['email'].isna() |
    clientes['genero'].isna() |
    clientes['fecha_nacimiento'].isna() |
    clientes['ciudad'].isna()
].copy()

Motivo Rechazo

In [28]:
def motivo(row):

    motivos = []

    if pd.isna(row['id_cliente']):
        motivos.append("id_cliente_vacio")

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['email']):
        motivos.append("email_vacio")

    if pd.isna(row['genero']):
        motivos.append("genero_vacio")

    if pd.isna(row['fecha_nacimiento']):
        motivos.append("fecha_nacimiento_invalida_o_vacia")

    if pd.isna(row['ciudad']):
        motivos.append("ciudad_vacia")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

rechazados

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento,motivo_rechazo
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,<na>,NaT,Santa Ana,<Na>,fecha_nacimiento_invalida_o_vacia
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Hombre,NaT,San Miguel,<Na>,fecha_nacimiento_invalida_o_vacia
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Hombre,NaT,Lalibertad,Regular,fecha_nacimiento_invalida_o_vacia
6,7,Diego Flores Rojas,diego.flores.rojas0@example.com,Hombre,NaT,Santaana,Premium,fecha_nacimiento_invalida_o_vacia
7,8,Karla Ortiz López,karla.ortiz.lopez1@mail.com,Hombre,NaT,Santaana,Premium,fecha_nacimiento_invalida_o_vacia
...,...,...,...,...,...,...,...,...
3025,3026,Ricardo Hernández Rojas (Dup),ricardo.hernandez.rojas3@gmail.com,Hombre,NaT,La Libertad,Regular,fecha_nacimiento_invalida_o_vacia
3026,3027,Luis Cruz Castillo (Dup),luis.cruz.castillo1@mail.com,<na>,NaT,San Salvador,Pyme,fecha_nacimiento_invalida_o_vacia
3027,3028,Jorge García Pérez (Dup),jorge.garcia.perez2@example.com,Hombre,NaT,San Miguel,<Na>,fecha_nacimiento_invalida_o_vacia
3028,3029,Juan García Rojas (Dup),juan.garcia.rojas4@example.com,fem,NaT,San Miguel,Pyme,fecha_nacimiento_invalida_o_vacia
3029,3030,Ana Vásquez Torres (Dup),ana.vasquez.torres5@gmail.com,female,NaT,La Libertad,Regular,fecha_nacimiento_invalida_o_vacia

Ver cuántos válidos y rechazados

In [29]:
print("Registros válidos:", len(validos))
print("Registros rechazados:", len(rechazados))

Registros válidos: 585
Registros rechazados: 2445

In [30]:
#Exportar archivos
validos.to_csv("clientes_curated.csv", index=False)

rechazados.to_csv("clientes_rejects.csv", index=False)

Instalar librerías para PostgreSQL y Conectar a BD

In [31]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_rivas:ks9EQNpC43n64cYY21G6e2BUn85omaRa@dpg-d6qu610gjchc73en58b0-a.oregon-postgres.render.com/etl_seguros_h814"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

Cargar tablas a PostgreSQL

In [35]:
validos.to_sql(
    'clientes_curated',
    engine,
    if_exists='replace',
    index=False
)

rechazados.to_sql(
    'clientes_rejects',
    engine,
    if_exists='replace',
    index=False
)

445

In [36]:
#Validar carga
pd.read_sql(
"SELECT * FROM clientes_curated LIMIT 10",
engine
)

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011-11-24,San Miguel,<Na>
1,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,<na>,1945-08-02,San Salvador,Pyme
2,6,Ricardo López Vásquez,ricardo.lopez.vasquez6@seguro.sv,Hombre,1966-10-15,Sonsonate,Pyme
3,13,Carlos Santos Morales,carlos.santos.morales6@correo.com,Hombre,1975-08-02,Santa Ana,Regular
4,17,Diego García Flores,diego.garcia.flores3@seguro.sv,Mujer,1980-06-10,L. Libertad,Vip
5,19,Ana Mendoza Ramírez,ana.mendoza.ramirez5@seguro.sv,<na>,1947-09-06,Santaana,Pyme
6,20,Paula López García,paula.lopez.garcia6@correo.com,female,1966-05-25,San Miguel,<Na>
7,28,Paula Castillo Santos,paula.castillo.santos0@gmail.com,Mujer,1978-06-21,San Salvador,Premium
8,33,Ricardo Chávez García,ricardo.chavez.garcia5@seguro.sv,Mujer,1993-08-26,San Miguel,Vip
9,46,Daniela Santos Reyes,daniela.santos.reyes4@seguro.sv,Hombre,1949-01-01,La Libertad,Premium