<a href="https://colab.research.google.com/github/AndreesArgueta/etl-data-pipeline/blob/main/etl_siniestros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/AndreesArgueta/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"

df = pd.read_csv(url)

df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

LIMPIEZA DE DATOS

In [2]:
siniestros = df.copy()

siniestros.columns = siniestros.columns.str.strip().str.lower()

for col in siniestros.select_dtypes(include="object").columns:
    siniestros[col] = siniestros[col].astype(str).str.strip()

siniestros = siniestros.replace(r'^\s*$', pd.NA, regex=True)

siniestros['fecha_siniestro'] = pd.to_datetime(
    siniestros['fecha_siniestro'],
    errors='coerce'
)

siniestros['monto_siniestro'] = (
    siniestros['monto_siniestro']
    .astype(str)
    .str.replace(",", "")
)

siniestros['monto_siniestro'] = pd.to_numeric(
    siniestros['monto_siniestro'],
    errors='coerce'
)

siniestros['estado'] = siniestros['estado'].str.title()

siniestros = siniestros.drop_duplicates()

/tmp/ipykernel_383/3764781310.py:10: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  siniestros['fecha_siniestro'] = pd.to_datetime(

SEPARAR DATOS VALIDOS Y RECHAZADOS

In [3]:
validos = siniestros[
    siniestros['id_siniestro'].notna() &
    siniestros['id_poliza'].notna() &
    siniestros['monto_siniestro'].notna()
].copy()

rechazados = siniestros[
    siniestros['id_siniestro'].isna() |
    siniestros['id_poliza'].isna() |
    siniestros['monto_siniestro'].isna()
].copy()

MOTIVO DE RECHAZO

In [4]:
def motivo(row):

    motivos = []

    if pd.isna(row['id_siniestro']):
        motivos.append("id_siniestro_vacio")

    if pd.isna(row['id_poliza']):
        motivos.append("id_poliza_vacio")

    if pd.isna(row['monto_siniestro']):
        motivos.append("monto_siniestro_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

EXPORTAR ARCHIVOS

In [5]:
validos.to_csv("siniestros_curated.csv", index=False)
rechazados.to_csv("siniestros_rejects.csv", index=False)

CONECTAR CON POSTGRESQL

In [6]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_argueta:RuSM0PkNryjJpjcJs9z3LwZNjP3Iuoph@dpg-d6qu6ivgi27c73aaaar0-a.oregon-postgres.render.com/etl_seguros_c75s"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 22.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

CARGAR DATOS CON POSTGRESQL

In [8]:
validos.to_sql(
    'siniestros_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'siniestros_rejects',
    engine,
    if_exists='append',
    index=False
)

943

VALIDAR LA CARGA

In [9]:
pd.read_sql(
"SELECT * FROM siniestros_curated LIMIT 10",
engine
)

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16       2092.59000    Abierto
1             2       2465             NaT       7076.25000    Abierto
2             3      15785      2025-09-19        702.27000    Cerrado
3             4      14299             NaT        274.63000    Abierto
4             5      12908             NaT       9377.69000  Rechazado
5             6       5107             NaT      10535.74000        Nan
6             7       3379             NaT      10513.30000    Abierto
7             8      23824      2025-01-17       2736.20000    Abierto
8            10      19947             NaT       8801.03000    Cerrado
9            11       6448             NaT          1.61938    Abierto